### PR TITLE
Always report the game is registered

### PR DESCRIPTION
**Pull request by Towerism**
Eliminate the need for a registration server or a registration file. Adjusted the Registration Client to always report that the game is registered.

### CODE REVIEW

**Comment by Towerism** [comment]
Unfortunately I can't rebuild the installers because the build system is coupled to some svn repository that I guess doesn't exist.

EDIT: looks like the problem is that `http://update.oddlabs.com/public_svnroot/games/tt` is dead.

**Comment by sunenielsen** [comment]
Thank you very much for your work on the game. However, we would like this repository to remain as the original source we released, and instead encourage you to fork the project with your own changes. We are happy to link to working projects that.

Regarding the svn repository, this was the technology used under the hood to release updates for the game (as a simple way of creating patches).

**Comment by Towerism** [comment]
Thank you for following up. I fully understand your intention to leave this repo as it is. The commit here is straight from my own fork. I created this pull request initially to make registration easier. But now I see that it can serve as documentation that the ant scripts' ability to produce installers (windows and osx) and install scripts (linux) may be broken due to the coupling of the scripts with the svn repo that no longer exists.

**Comment by Towerism** [comment]
To be more clear about the possible brokenness, here is where an error occurs when I run `ant assembleinstaller`:

```
-checkoutgamedata:
    [mkdir] Created dir: /home/mfracker/tribaltrouble/tt/build/installers/assembly/common/gamedata/data-1
     [java] error: Authentication challenge is not supported:
     [java] null
     [java] org.tmatesoft.svn.core.io.SVNAuthenticationException: Authentication challenge is not supported:
     [java] null
     [java]     at org.tmatesoft.svn.core.internal.io.dav.HttpConnection.sendRequest(HttpConnection.java:253)
     [java]     at org.tmatesoft.svn.core.internal.io.dav.HttpConnection.sendRequest(HttpConnection.java:210)
     [java]     at org.tmatesoft.svn.core.internal.io.dav.HttpConnection.request(HttpConnection.java:196)
     [java]     at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.open(DAVConnection.java:63)
     [java]     at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.openConnection(DAVRepository.java:311)
     [java]     at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.getLatestRevision(DAVRepository.java:67)
     [java]     at org.tmatesoft.svn.core.io.SVNRepository.checkout(SVNRepository.java:185)
     [java]     at org.tmatesoft.svn.core.internal.SVNWorkspace.checkout(SVNWorkspace.java:283)
     [java]     at org.tmatesoft.svn.cli.command.CheckoutCommand.run(CheckoutCommand.java:68)
     [java]     at org.tmatesoft.svn.cli.SVN.main(SVN.java:61)
```

**Pull request closed without merging**
